[package]
name = "rusty_paseto"
version = "0.1.0"
edition = "2018"
resolver = "2"

[dependencies]
blake2 = { version = "^0.9.2"}
chacha20poly1305 = { version = "^0.9.0"}
ring = { version = "^0.16", features = ["std"] }
base64 = "^0.13.0" 
hex = "^0.4.3"
serde_json = { version = "^1.0.68"}
thiserror = "1.0.29"

[dev-dependencies]
