[package]
name = "rusty_paseto"
version = "0.2.2"
edition = "2021"
rust-version = "1.57.0"

[lib]
#doctest = false


[dependencies]
chacha20 = "0.8.1"
blake2 = { version = "^0.9.2"}
chacha20poly1305 = { version = "^0.9.0"}
ring = { version = "^0.16", features = ["std"] }
base64 = "^0.13.0" 
hex = "^0.4.3"
serde= { version = "1.0.117", features = ["derive"] }
ed25519-dalek = "1.0.1"
serde_json = { version = "^1.0.68"}
thiserror = "1.0.29"
iso8601 = "0.4.0"
erased-serde = "0.3.16"
chrono = "0.4.19"
aes = {version = "0.7.5", features = ["ctr"]}
hmac = "0.11.0"
sha2 = "0.9.8"
zeroize = {version = "1.4.3", features = ["zeroize_derive"]}

[dev-dependencies]
anyhow = "1.0.45"
primes = "0.3.0"
