[package]
name = "rusty_paseto"
version = "0.2.5"
edition = "2021"
readme = "readme.md"
authors = ["Roland Rodriguez <rolandrodriguez@gmail.com"]
description = "A type-driven, ergonomic implementation of the PASETO protocol for secure stateless tokens."
repository = "https://github.com/rrrodzilla/rusty_paseto"
license = "MIT OR Apache-2.0"
keywords = ["crypto", "cryptography", "authentication", "paseto", "token", "security", "api", "web"]
categories = ["cryptography", "authentication", "encoding", "network-programming", "web-programming"]

[lib]
#doctest = false


[dependencies]
chacha20 = "0.8.1"
blake2 = { version = "^0.9.2"}
chacha20poly1305 = { version = "^0.9.0"}
ring = { version = "^0.16", features = ["std"] }
base64 = "^0.13.0" 
hex = "^0.4.3"
serde= { version = "1.0.117", features = ["derive"] }
ed25519-dalek = "1.0.1"
serde_json = { version = "^1.0.68"}
thiserror = "1.0.29"
iso8601 = "0.4.0"
erased-serde = "0.3.16"
aes = {version = "0.7.5", features = ["ctr"]}
hmac = "0.11.0"
sha2 = "0.9.8"
zeroize = {version = "1.4.3", features = ["zeroize_derive"]}
time = {version =  "0.3.5", features = ["parsing", "formatting"]}

[dev-dependencies]
anyhow = "1.0.45"
primes = "0.3.0"
